// Auto-generated by Supabase CLI
// This is a placeholder - run `supabase gen types typescript` to generate full types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      knowledge_sources: {
        Row: {
          id: string
          name: string
          source_type: string
          url: string
          base_domain: string
          category: string
          scrape_enabled: boolean
          scrape_frequency: string
          last_scraped_at: string | null
          next_scrape_at: string | null
          priority: number
          quality_score: number
          trust_level: string
          status: string
          error_count: number
          last_error: string | null
          tags: string[]
          notes: string | null
          created_at: string
          updated_at: string
          created_by: string
        }
        Insert: Partial<Database['public']['Tables']['knowledge_sources']['Row']>
        Update: Partial<Database['public']['Tables']['knowledge_sources']['Row']>
      }
      knowledge_content: {
        Row: {
          id: string
          source_id: string
          url: string
          title: string
          content_type: string
          content: string
          raw_html: string | null
          markdown: string | null
          code_snippets: Json
          author: string | null
          published_at: string | null
          word_count: number
          character_count: number
          processed: boolean
          processed_at: string | null
          embedding_generated: boolean
          usefulness_score: number
          accuracy_verified: boolean
          keywords: string[]
          topics: string[]
          content_hash: string
          version: number
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['knowledge_content']['Row']>
        Update: Partial<Database['public']['Tables']['knowledge_content']['Row']>
      }
      scraping_jobs: {
        Row: {
          id: string
          source_id: string
          job_type: string
          scheduled_at: string
          started_at: string | null
          completed_at: string | null
          status: string
          total_urls: number
          urls_processed: number
          urls_failed: number
          progress_percentage: number
          items_scraped: number
          items_new: number
          items_updated: number
          items_unchanged: number
          error_message: string | null
          retry_count: number
          max_retries: number
          duration_seconds: number | null
          avg_time_per_url: number | null
          config: Json
          results: Json
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['scraping_jobs']['Row']>
        Update: Partial<Database['public']['Tables']['scraping_jobs']['Row']>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
